DROP TABLE IF EXISTS claim_case_cal_core;
CREATE TABLE claim_case_cal_core
(
    rpt_no               VARCHAR(20)    NOT NULL COMMENT '报案号',
    case_status          VARCHAR(2)     NOT NULL COMMENT '案件状态',
    is_appeal            VARCHAR(2) COMMENT '是否申诉案件',
    bill_amount          DECIMAL(16, 2) NOT NULL COMMENT '账单金额',
    hos_discount_amount  DECIMAL(16, 2) NOT NULL COMMENT '医疗折扣金额',
    ss_advance_payment   DECIMAL(16, 2) COMMENT '社保先期给付',
    tp_advance_payment   DECIMAL(16, 2) COMMENT '第三方先期给付',
    trans_Serial_copay   DECIMAL(16, 2) COMMENT '非交易流水自付额',
    copay                DECIMAL(16, 2) COMMENT '驻点收取自付额',
    bill_currency        VARCHAR(5)     NOT NULL COMMENT '账单币种',
    treatment_start_date DATE           NOT NULL COMMENT '汇率转换日期',
    organ_code           VARCHAR(20)    NOT NULL COMMENT '受理机构',
    appeal_serial        int(2) NOT NULL COMMENT '申诉序号',
    trans_serial_no      varchar(30) VARCHAR COMMENT '自付额流水号',
    cal_amount           DECIMAL(16, 2) NOT NULL COMMENT '理算金额',
    pay_amount           DECIMAL(16, 2) NOT NULL COMMENT '支付金额',
    exchange_rate        DECIMAL(16, 10) COMMENT '汇率',
    pay_amount_foreign   DECIMAL(16, 2) COMMENT '外币支付金额',
    request_id           varchar(32) COMMENT '请求ID',
    response_id          varchar(32) COMMENT '响应ID',
    old_response_id      varchar(32) COMMENT '原响应ID',
    status               VARCHAR(1) null comment '数据状态（Y-有效，N-无效）',
    create_by            VARCHAR(20)    NOT NULL COMMENT '创建人',
    create_time          DATETIME       NOT NULL COMMENT '创建时间',
    update_by            VARCHAR(20) COMMENT '更新人',
    update_time          DATETIME COMMENT '更新时间',
    PRIMARY KEY (rpt_no)
) engine=innodb auto_increment=100 COMMENT = '核心案件同步信息表';